### ISSUE TITLE
Some pages cannot be deleted while they can be edited (normal maybe?)

### ISSUE THREAD

**Issue by asheenlevrai** [dregad/dokuwiki-plugin-deletepagebutton#9] opened 2021-06-23 09:03 UTC
Hi :)

I am currently using a form made with the Bureaucracy plugin in order to create wiki pages from a template.
The newly created pages contain data that were input by the users via the form.

Now, these newly created pages cannot be deleted by pressing the "delete page" button from your plugin.
The button works well for other (regular?) pages, though.
These pages can normally be edited using the "edit this page" button.
I can delete these pages by editing them and deleting the whole content of the page (as usual when not using your plugin).

I suspect this is not a problem of your plugin but rather something special with these pages since the same "issue" is present with the plugin [Move](https://www.dokuwiki.org/plugin:move). Similarly, the "rename page" button has no effect on these pages.

Any idea why these pages are special and how?

Thank you very much in advance for your help.
Best,
-a-

**Comment by dregad** [comment] 2022-06-08 06:59
@asheenlevrai apologies for the late reply, I see your question only today.

Unfortunately, I have no idea why the plugin would be unable to delete some pages, and I am not able to reproduce the behavior. 

As you said, this is probably not caused by the plugin, which is basically just saving the page with empty text.

I'm going to close this, but feel free to reopen if you can provide additional information and a reproducible test case.

**Closed as completed by dregad** 2022-06-08 06:59 UTC

**Comment by asheenlevrai** [comment] 2022-06-08 07:08
ok. thanks
